version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: six
    versions:
    - 1.15.0
  - dependency-name: wtforms
    versions:
    - 2.3.3
  - dependency-name: pycparser
    versions:
    - "2.20"
  - dependency-name: urllib3
    versions:
    - 1.24.2
    - 1.26.4
  - dependency-name: requests
    versions:
    - 2.25.1
  - dependency-name: pyyaml
    versions:
    - 5.4.1
  - dependency-name: werkzeug
    versions:
    - 0.15.5
  - dependency-name: certifi
    versions:
    - 2020.12.5
  - dependency-name: chardet
    versions:
    - 4.0.0
  - dependency-name: psycopg2
    versions:
    - 2.8.6
  - dependency-name: click
    versions:
    - 7.1.2
  - dependency-name: idna
    versions:
    - "3.1"
  - dependency-name: flask-login
    versions:
    - 0.5.0
  - dependency-name: flask-wtf
    versions:
    - 0.14.3
  - dependency-name: sqlalchemy
    versions:
    - 1.3.22
    - 1.3.23
    - 1.4.0
    - 1.4.1
    - 1.4.2
    - 1.4.3
    - 1.4.4
    - 1.4.5
    - 1.4.6
    - 1.4.7
    - 1.4.8
  - dependency-name: flask-sqlalchemy
    versions:
    - 2.4.4
    - 2.5.0
  - dependency-name: cffi
    versions:
    - 1.14.4
  - dependency-name: scout-apm
    versions:
    - 2.17.0
  - dependency-name: gunicorn
    versions:
    - 20.0.4
  - dependency-name: jinja2
    versions:
    - 2.10.1
