INSERT INTO "Tag" (name) VALUES
	('HTML'),
	('Python'),
	('sushi'),
	('movies'),
	('video games'),
	('Unity'),
	('Java'),
	('AI'),
	('animations'),
	('documentaries'),
	('Fallout 3'),
	('Fallout: New Vegas'),
	('Bob''s Burgers'),
	('Planet of the Apes (1968)'),
	('Back to the Future (trilogy)'),
	('CSS'),
	('cats'),
	('old animals'),
	('mental health issues'),
	('OCD'),
	('Rick & Morty'),
	('science'),
	('research'),
	('Asperger''s Syndrome'),
	('University of Helsinki'),
	('computer science'),
	('Finland'),
	('full-stack'),
	('JavaScript'),
	('HTML5'),
	('CSS3'),
	('Bootstrap'),
	('JetBrains PyCharm'),
	('binary'),
	('hexadecimal'),
	('badminton'),
	('Super Mario Bros.'),
	('Halo'),
	('philosophy'),
	('UAV'),
	('electric cars'),
	('drones'),
	('puzzles');